add example for inverse and forward kinematics + fix typo
Kinovarobotics/kortex pull request #67
Opened 2021-06-10 15:01 UTC by felixmaisonneuve

2021-06-11 15:40 UTC, alexvannobel requested changes

2021-06-11 15:40 UTC, alexvannobel commented on api_cpp/examples/111-Kinematics/01-compute-kinematics.cpp
> +    return true;
Can you try/catch this whole function (or both calls to `base`)?
Those calls can throw and the function should print the exception as well as `return false;` when an error happens

2021-06-11 15:40 UTC, alexvannobel commented on api_cpp/examples/111-Kinematics/01-compute-kinematics.cpp
> +    return true;
same comment for try/catch

2021-06-11 15:40 UTC, alexvannobel commented on api_python/examples/111-kinematics/01-compute-kinematics.py
> +    return True
same comment for try/except

2021-06-11 15:40 UTC, alexvannobel commented on api_python/examples/111-kinematics/01-compute-kinematics.py
> +    print("Coordinate (x, y, z)  : (", pose.x, ", ", pose.y, ", ", pose.z, ")")
I think it is cleaner to use `format` when printing variables in string as such : 
`print("Coordinate (x, y, z) : ({}, {}, {})".format(pose.x, pose.y, pose.z))`

2021-06-11 15:40 UTC, alexvannobel commented on api_python/examples/111-kinematics/01-compute-kinematics.py
> +    return True
same comment for try/except

2021-06-14 12:10 UTC, alexvannobel requested changes

2021-06-14 12:10 UTC, alexvannobel commented on api_cpp/examples/111-Kinematics/01-compute-kinematics.cpp
> +    if(success) success &= example_inverse_kinematics(base);
I don't think an if is needed here since a chain of `&=` will always yield `false` if one of the values is `false`.

2021-06-14 12:10 UTC, alexvannobel commented on api_cpp/examples/111-Kinematics/01-compute-kinematics.cpp
> +void printException(k_api::KDetailedException& ex)
just a detail but using a const ref is a bit cleaner
`const k_api::KDetailedException& ex`

2021-06-14 12:10 UTC, alexvannobel commented on api_python/examples/111-kinematics/01-compute-kinematics.py
> +        if success : success &= example_inverse_kinematics(base)
same comment for the if here

2021-06-14 12:59 UTC, alexvannobel approved these changes

2021-06-14 13:03 UTC, felixmaisonneuve commented on api_cpp/examples/111-Kinematics/01-compute-kinematics.cpp
> +void printException(k_api::KDetailedException& ex)
You can't because `getErrorInfo()` is not `const` so it is not compatible

2021-06-16 18:56 UTC, alexvannobel approved these changes

2021-06-16 19:27 UTC, merged